### PR TITLE
Adds french translation and split policies into 2 different languages

### PR DESCRIPTION
**Pull request by mlhamel**
My goal is to add complete translation of the site. For now, in this PR i've just splitted the policies into 2 different files but we still need to implement a mechanism for the loading.

i thought it could as simple as adding a new domain, something like `notrepolitique.ca`, default would be to load the english version and if we are on the french domain, the french translation would loaded.

Please note that i've changed the order of the topics by reindenting the json files.

### CODE REVIEW

**Comment by mlhamel** [comment]
Also, i'm not translating the references or the details. Elections is arriving very quickly, my goal would be to have something minimal working :)

**Comment by jahfer** [comment]
Oh wow this is fantastic! I would love to have launched with french content, but alas I only know English :) Thanks for this contribution. I'll see about getting a proper french version up ASAP.

**Comment by jahfer** [comment]
> Please note that i've changed the order of the topics by reindenting the json files.

Sorry, not sure I follow why the order of the topics was changed. Was it automated?

**Comment by mlhamel** [comment]
Basically i've used a json formater to reident and reformat the json file but i've discovered afterward that it change the ordering of the different topics. What do you think ? Do you want to revert back to the previous ordering ?

**Comment by jahfer** [comment]
Yeah, I'd like to keep the original order if possible. Also I tried your branch and it worked well except that we'll need to get rid of the [trailing commas](https://github.com/mlhamel/ourpolitics/blob/98292181edafe44867cdc3f9dc8aa50739521ef4/app/data/policies/fr.json#L29) on the french summary. The browser chokes on parsing that for some reason. If you could update the JSON with those commas gone and the original ordering, I can merge this now :) 

Thanks again for your effort! I spent some time yesterday making the code a bit more language-agnostic so it plays nicer.

**Comment by mlhamel** [comment]
Ok i've the trailing commas error AND the ordering of `en` and `fr` data.

The french one will not loading currently cause there is no mechanism for loading the right translated party names but i'm planning to do it in another PR :)

**Pull request merged**
